### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mbaechtold** [jone/github-watchlist#10]
Hey @jone 

Would you be interested in a pull request which makes the code base compatible with Python > 3.6 and drops compatibility for older Pythons?

**Comment by jone** [comment]
I'm no longer using `github-watchlist` myself. So feel free to do whatever you like 😉

**Comment by mbaechtold** [comment]
Closing this issue due to its age.

**Comment by ryanwebjackson** [comment]
@mbaechtold I am looking at this myself - Looks like the 'setuptools' lib has changed substantially, and no longer works as-is.
